package com.ainions.nion.domain.enums;

public enum L3Agent {
    ACTION_ITEM_EXTRACTION,
    RISK_TRACKING,
    DECISION_TRACKING,
    PROGRESS_MONITORING,
    DEADLINE_MANAGEMENT,
    MESSAGE_DELIVERY,
    STAKEHOLDER_NOTIFICATION,
    MEETING_SUMMARY,
    ESCALATION_HANDLER,
    QNA,
    RETROSPECTIVE_ANALYSIS,
    PATTERN_RECOGNITION,
    KNOWLEDGE_BASE_UPDATE,
    IMPROVEMENT_SUGGESTIONS,
    KNOWLEDGE_RETRIEVAL,
    EVALUATION
}
